### ISSUE TITLE
consider rename of sample

### ISSUE THREAD

**Issue by derekxkwan** [tidalcycles/Dirt-Samples#13]
I've come across a sample that comes alphabetically in between `chin` and `circus` that could be taken under consideration renaming. Despite the usage in the common idiom referring to a gap in one's armor, the term also unfortunately has the common usage as a racial slur. Although I don't think that's the intent here (but rather onomatopoeic), I'd be hesitant to type out the word (def in a live coding performance setting even though I don't think I'm quite there just yet...). The sample sounds somewhat like keys, coins, or a small metal chain being dropped in a dish, perhaps something like `keys` or `coins` could be used instead? Thanks!

**Comment by kindohm** [comment]
@derekxkwan thanks for submitting this. I changed the sample name in #14.

**Comment by derekxkwan** [comment]
awesome, thx!
