### ISSUE TITLE
re-organize or remove unplayable sub-folders

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/Dirt-Samples#3]
The sub-folders (e.g. the 808s) aren't playable in their current structure and cause unnecessary confusion for new users.

**Comment by telephon** [comment]
what makes them unplayable?

**Comment by kindohm** [comment]
There is no Tidal syntax that exists to access or play these samples. I also don't know if Dirt (classic Dirt, specifically) would support it.

When I run classic Dirt with the following:

`./dirt --samples-root-path ~/samples`

There is no way to play the following samples:

`~/samples/808/bd`
`~/samples/808/mt`
`~/samples/808/ch`

There is no syntax in Tidal to get at the `bd`, `mt`, or `ch` sub folders of `808`.

Of course, a Tidal feature could be added to play these sub-folder samples. Maybe that would be better than re-organizing this repository.

**Comment by lennart** [comment]
those samples are in a subdirectory of a subdirectory, so you cannot specify them via e.g. "808/BD:2" to load the third sample from `808/BD` mostly because `/` is reserved within the EDSL. however people love 808 so this trips people new to tidal.

**Comment by lennart** [comment]
oops, too slow, thx @kindohm

**Comment by kindohm** [comment]
Yes, those 808 samples are attractive and new users try to use them immediately, but are confused why they don't work.

**Comment by telephon** [comment]
OK, you could load them by just passing in that path with a `/*/*`. But there might be collisions. Better perhaps to just move them, right? or what would be your idea?

**Comment by telephon** [comment]
Just let me know when the branch is ready to be merged – looks good already!

**Comment by yaxu** [comment]
Oops I took your other comment as a request for someone else to merge, agree looks good!

**Comment by don-smith** [comment]
Thanks for the merge! This issue has been resolved and can be closed.
